services:
  - type: web
    name: rasa-bot
    runtime: python
    pythonVersion: 3.10.12
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      rasa run --enable-api --cors "*" -p 5005
